CREATE TABLE payroll_management.personnel_attendance (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `attendance_date` date DEFAULT NULL,
  `attendance_day_of_week` varchar(255) DEFAULT NULL,
  `iclock_transaction_id` bigint DEFAULT NULL,
  `staff_id` bigint DEFAULT NULL,
  `punch_event` varchar(255) DEFAULT NULL,
  `punch_timestamp` datetime(6) DEFAULT NULL,
  `terminal_serial_number` varchar(255) DEFAULT NULL,
  `upload_source` varchar(255) DEFAULT NULL,
  `sequence_number_of_punch` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_timestamp` datetime(6) DEFAULT NULL,
  `modified_by` bigint DEFAULT NULL,
  `modified_timestamp` datetime(6) DEFAULT NULL,
  `application_name` varchar(255) DEFAULT NULL,
  `store_id` bigint DEFAULT NULL,
  `tenant_id` bigint DEFAULT NULL,
  `current_status` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `version_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`)
);
